// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmktoqbagvtuwdlzvmec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRta3RvcWJhZ3Z0dXdkbHp2bWVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNjc0NDgsImV4cCI6MjA2NDc0MzQ0OH0.vaYlaxELiCV8qyXdvC-B1LrjZ6xdoPgOMXFO6OVeIsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);